<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>CampaignPanel.API</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\CampaignPanel.Domain\CampaignPanel.Domain.csproj" />
    <ProjectReference Include="..\CampaignPanel.Application\CampaignPanel.Application.csproj" />
    <ProjectReference Include="..\CampaignPanel.Infrastructure\CampaignPanel.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.5.0" />
  </ItemGroup>
</Project>
